### PR TITLE
Unpin xarray, add kmuehlbauer as maintainer

### PR DESCRIPTION
**Pull request by kmuehlbauer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by ghiggi** [comment]
Hi @kmuehlbauer ! Any idea why this is not passing? 
Once this is merged, I can attempt to make a new release tomorrow with also the code needed for the SR/GR validation ;)

**Comment by kmuehlbauer** [comment]
It would have to be changed upstream, too. I can do a PR.

**Comment by kmuehlbauer** [comment]
@ghiggi See https://github.com/ghiggi/gpm_api/pull/61

**Comment by ghiggi** [comment]
I take care of all this tomorrow if fine for you ;)

**Pull request closed without merging**
